taskkill /f /im JaGuarWaveTestPlatform.exe
taskkill /f /im JaGuarWaveHelp.exe
taskkill /f /im JGW_EquipConfig.exe
taskkill /f /im JGW_LossConfigTools.exe
taskkill /f /im JGW_MESServiceApplication.exe
taskkill /f /im JGW_WlanServiceApplication.exe
taskkill /f /im JGW_LogCat.exe
taskkill /f /im JGW_SSHDemo.exe
taskkill /f /im TSEAPSUpgradeTool.exe
taskkill /f /im TSEDownload.exe
exec\adb.exe kill-server
taskkill /f /im adb.exe
taskkill /f /im fastboot.exe
taskkill /f /im fh_loader.exe
taskkill /f /im QSaharaServer.exe
taskkill /f /im TSEDownload.exe
taskkill /f /im ProductScreenTool.exe
taskkill /f /im prs_download_flash.exe
taskkill /f /im iperf.exe
taskkill /f /im iperf3.exe
taskkill /f /im cmd.exe