;; Settings relavant to the MultiDut_1Proc_MultiThrd_SuiteClient tool
;; Format:
;;    <setting_name>=<value>
[Settings]
SuiteTestManager=C:\Program Files (x86)\Qualcomm\QDART\bin\SuiteTestManager.dll

;; Environment variables are equivalent of QSPR global variables.  These are applied to all phones listed under 'DUT_Config'.
;; Format:
;;    <env_name>=<value>
[Environment]
XTT_TIMEOUT=1000
MULTIPLEX_MANAGER_CONFIG_FILE=C:\Program Files (x86)\Qualcomm\QDART\databases\MultiplexManagerConfigFile.xml

;; Reference libraries allows the user to associate the software tool name with
;; path and location of the DLL.  Multiple technologies can be specified however
;; the names should be unique.
;; Format:
;;    <user-defined_technology_name>=<absolute_path_to_dll>
[Reference_Libraries]
RFCalibration=C:\Program Files (x86)\Qualcomm\QDART\bin\SubSysRFCalibration_Server.dll
;RFCalibration=C:\HTE\QDART\SUITE\SubSysRFCalibration\SubSysRFCalibration_Server\STI_XRelease_DLL\SubSysRFCalibration_Server.dll
QSEQ=C:\Program Files (x86)\Qualcomm\QDART\bin\QSEQ_Core_Server.dll

;; DUT configuration allows the user to specify one or more DUT(s) to test.
;; Each line entry represents a single DUT.  Multiple DUT(s) are configured
;; by adding multiple line entries.
;; Format:
;; <dut_index>=<com_port>,<uutid>;<user-defined_technology_name>,<xtt>;<user-defined_technology_name>,<xtt>;<user-defined_technology_name>,<xtt>...
[DUT_Config]
1=38,DUT_1;RFCalibration,C:\Perforce\eshyu_ESHYU2_4265\source\qcom\qct\modem\rftarget\dime\main\latest\common\xtt\etc\MSM8974-WTR1625_NAEU_CA__MTP__C_G_W_L_ESC_ET__Xvc__RFCal1.0_ESHYU2.xtt
2=34,DUT_2;RFCalibration,C:\Perforce\eshyu_ESHYU2_4265\source\qcom\qct\modem\rftarget\dime\main\latest\common\xtt\etc\MSM8974-WTR1625_NAEU_CA__MTP__C_G_W_L_ESC_ET__Xvc__RFCal1.0_ESHYU2.xtt

