[MAIN]
AllTestInfoTitle=Table of Contents
TableHrefFormat=<a name="%d" xmlns:msxsl="urn:schemas-microsoft-com:xslt">
StartTableFlag=<table border="1">
EndTableFlag=</table>
ResolveTestProject=LTE_MaxPower,LTE_TxQuality,LTE_OccupiedBandwidth,LTE_SpectrumEmissionMask,LTE_ACLR,LTE_TxPower,LTE_RFCalVerification_Rx0,LTE_RFCalVerification_Rx1,LTE_EstimatedSensitivity_Rx0,LTE_EstimatedSensitivity_Rx1

[LTE_MaxPower]
TableTitles=LTE_MaxPower
LTE_MaxPower=Band (),Channel (),Ch_BW (MHz),UL_Start_RB (),UL_Num_RB (),AvgTxPwr (dBm),AvgTxPwr Min,AvgTxPwr Max
LTE_MaxPower_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">LTE_MaxPower</b>
LTE_MaxPower_Show=LTE_MaxPower Band:{0},Channel:{1},{2},{3},{4},TxPwr:{5}({6} ~ {7})

[LTE_TxQuality]
TableTitles=LTE_TxQuality,Freq Error,EVM,Origin Offset,Spectrum Flatness
LTE_TxQuality=Band (),Channel (),Ch_BW (MHz),UL_Start_RB (),UL_Num_RB (),AvgTxPwr (dBm),AvgTxPwr Min,AvgTxPwr Max
LTE_TxQuality_Show=LTE_TxQuality Band:{0},Channel:{1},{2},{3},{4},TxPwr:{5}({6} ~ {7})


Freq Error=UL_Desc (),OriginalFreqErr (ppm),OriginalFreqErrHz (Hz),AvgFreqErr (ppm),AvgFreqErr Min,AvgFreqErr Max,ExtremeFreqErr (ppm),ExtremeFreqErr Min,ExtremeFreqErr Max
Freq Error_Show=LTE Freq Error {0},OriginalFreqErr:{1},OriginalFreqErrHz:{2},AvgFreqErr:{3}({4} ~ {5}),ExtremeFreqErr:{6}({7} ~ {8})

EVM=UL_Desc (),AvgEVM (%),AvgEVM Max,MaxEVM (%),MaxEVM Max,AvgEVM_DMRS (%),AvgEVM_DMRS Max,MaxEVM_DMRS (%),MaxEVM_DMRS Max
EVM_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">EVM</b>
EVM_Show=LTE EVM {0},AvgEVM:{1}( ~ {2}),MaxEVM:{3}( ~ {4}),AvgEVM_DMRS:{5}( ~ {6}),MaxEVM_DMRS:{7}( ~ {8})

Origin Offset=UL_Desc (),_AvgOrigOffset_ (dBc),_AvgOrigOffset_ Max,_MaxOrigOffset_ (dBc),_MaxOrigOffset_ Max
Origin Offset_Show={0},_AvgOrigOffset_:{1}( ~ {2}),_MaxOrigOffset_:{3}( ~ {4})

Spectrum Flatness=UL_Desc (),Spec Flat R1 (dB p-p),Spec Flat R1 Max,Spec Flat R2 (dB p-p),Spec Flat R2 Max,Spec Flat R12 (dB),Spec Flat R12 Max,Spec Flat R21 (dB),Spec Flat R21 Max
Spectrum Flatness_Show=LTE Spectrum Flatness {0},Spec Flat R1:{1}( ~ {2}),Spec Flat R2:{3}( ~ {4}),Spec Flat R12:{5}( ~ {6}),Spec Flat R21:{7}( ~ {8})

[LTE_OccupiedBandwidth]
TableTitles=OBW
OBW=Band (),Channel (),Ch_BW (MHz),UL_Start_RB (),UL_Num_RB (),MaxOccupiedBW (MHz),MaxOccupiedBW Max
OBW_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">OBW</b>
OBW_Show=LTE OBW Band:{0},Channel:{1},{2},{3},{4},MaxOccupiedBW:{5}( ~ {6})

[LTE_SpectrumEmissionMask]
TableTitles=SEM_Detail

;SEM=Band (),Channel (),Ch_BW (MHz),UL_Start_RB (),UL_Num_RB 
;SEM_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">SEM</b>
;SEM_Show=

SEM_Detail=UL_Desc (),OOB Power (dBm),OOB Power Max
SEM_Detail_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">SEM_Detail</b>
SEM_Detail_Show=LTE SEM {0},OOB Power:{1}( ~ {2})

[LTE_ACLR]
TableTitles=UTRA ACLR

UTRA ACLR=Band (),Channel (),Ch_BW (MHz),UL_Start_RB (),UL_Num_RB (),UTRA ACLR (dB),UTRA ACLR Min,UTRA ACLR Extreme (dB),UTRA ACLR Extreme Min,E-UTRA_ACLR (),E-UTRA_ACLR Min,E-UTRA_ACLR_Extreme (),E-UTRA_ACLR_Extreme Min
UTRA ACLR_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">UTRA ACLR</b>
UTRA ACLR_Show=LTE ACLR Band:{0},Channel:{1},{2},{3},{4},UTRA ACLR:{5}({6} ~ ),UTRA ACLR Extreme:{7}({8} ~ ),E-UTRA_ACLR:{9}({10} ~ ),E-UTRA_ACLR_Extreme:{11}({12} ~ )

[LTE_TxPower]
TableTitles=LTE_TxPower

LTE_TxPower=Band (),Channel (),Ch_BW (MHz),UL_Start_RB (),UL_Num_RB (),AvgTxPwr (dBm),AvgTxPwr Min,AvgTxPwr Max
LTE_TxPower_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">LTE_TxPower</b>
LTE_TxPower_Show=LTE_TxPower Band:{0},Channel:{1},{2},{3},{4},TxPwr:{5}({6} ~ {7})

[LTE_RFCalVerification_Rx0]
TableTitles=LTE_RFCalVerification_Rx0
LTE_RFCalVerification_Rx0=Band (),Channel (),Ch_BW (MHz),UL_Start_RB (),UL_Num_RB (),RxError0 (dB),RxError0 Min,RxError0 Max,RxAGC0 (dBm),RxAGC0 Min,RxAGC0 Max
LTE_RFCalVerification_Rx0_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">LTE_RFCalVerification</b>
LTE_RFCalVerification_Rx0_Show=LTE RX0 Band:{0},Channel:{1},{2},{3},{4},RxError0:{5}({6} ~ {7}),RxAGC0:{8}({9} ~ {10})


[LTE_RFCalVerification_Rx1]
TableTitles=LTE_RFCalVerification_Rx1
LTE_RFCalVerification_Rx1=Band (),Channel (),Ch_BW (MHz),UL_Start_RB (),UL_Num_RB (),RxError1 (dB),RxError1 Min,RxError1 Max,RxAGC1 (dBm),RxAGC1 Min,RxAGC1 Max
LTE_RFCalVerification_Rx1_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">LTE_RFCalVerification</b>
LTE_RFCalVerification_Rx1_Show=LTE RX1 Band:{0},Channel:{1},{2},{3},{4},RxError1:{5}({6} ~ {7}),RxAGC1:{8}({9} ~ {10})

[LTE_EstimatedSensitivity_Rx0]
TableTitles=LTE_EstimatedSensitivity_Rx0
LTE_EstimatedSensitivity_Rx0=Band (),Channel (),Ch_BW (MHz),UL_Start_RB (),UL_Num_RB (),Rx Level (dBm),Rx Level Min,Rx Level Max,CtoN  (dB),CtoN  Min,CtoN_Max (dB),CtoN_Min (dB),CtoN_MaxtoMin_Delta (dB),CtoN_MaxtoMin_Delta Max,Sensitivity (dBm),Sensitivity Max
LTE_EstimatedSensitivity_Rx0_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">LTE_EstimatedSensitivity</b>
LTE_EstimatedSensitivity_Rx0_Show=LTE RX0 Band:{0},Channel:{1},{2},{3},{4},Rx Level:{5}({6} ~ {7}),CtoN:{8}({9} ~ ),CtoN_MaxtoMin_Delta:{10}-{11}={12}{ ~ {13}},Sensitivity:{14}( ~ {15})

[LTE_EstimatedSensitivity_Rx1]
TableTitles=LTE_EstimatedSensitivity_Rx1
LTE_EstimatedSensitivity_Rx1=Band (),Channel (),Ch_BW (MHz),UL_Start_RB (),UL_Num_RB (),Rx Level (dBm),Rx Level Min,Rx Level Max,CtoN  (dB),CtoN  Min,CtoN_Max (dB),CtoN_Min (dB),CtoN_MaxtoMin_Delta (dB),CtoN_MaxtoMin_Delta Max,Sensitivity (dBm),Sensitivity Max
LTE_EstimatedSensitivity_Rx1_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">LTE_EstimatedSensitivity</b>
LTE_EstimatedSensitivity_Rx1_Show=LTE RX1 Band:{0},Channel:{1},{2},{3},{4},Rx Level:{5}({6} ~ {7}),CtoN:{8}({9} ~ ),CtoN_MaxtoMin_Delta:{10}-{11}={12}{ ~ {13}},Sensitivity:{14}( ~ {15})

