[MAIN]
AllTestInfoTitle=Table of Contents
TableHrefFormat=<a name="%d" xmlns:msxsl="urn:schemas-microsoft-com:xslt">
StartTableFlag=<table border="1">
EndTableFlag=</table>
ResolveTestProject=LTE_MaxPower,LTE_TxQuality,LTE_OccupiedBandwidth,LTE_SpectrumEmissionMask,LTE_ACLR,LTE_TxPower,LTE_RFCalVerification_Rx0,LTE_RFCalVerification_Rx1,LTE_EstimatedSensitivity_Rx0,LTE_EstimatedSensitivity_Rx1,NR5G_MaxPower,NR5G_RFCalVerification,NR5G_TxMod,NR5G_TxOBW,NR5G_TxSEM,NR5G_TxACLR,NR5G_RFCalVerification_Rx0,NR5G_RFCalVerification_Rx1,NR5G_RFCalVerification_Rx2,NR5G_RFCalVerification_Rx3,NR5G_EstimatedSensitivity_Rx0,NR5G_EstimatedSensitivity_Rx1,NR5G_EstimatedSensitivity_Rx2,NR5G_EstimatedSensitivity_Rx3

[LTE_MaxPower]
TableTitles=LTE_MaxPower
LTE_MaxPower=Band (),Channel (),Ch_BW (MHz),UL_Start_RB (),UL_Num_RB (),AvgTxPwr (dBm),AvgTxPwr Min,AvgTxPwr Max
LTE_MaxPower_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">LTE_MaxPower</b>
LTE_MaxPower_Show=LTE_MaxPower Band:{0},Channel:{1},{2},{3},{4},TxPwr:{5}({6} ~ {7})

[LTE_TxQuality]
TableTitles=LTE_TxQuality,Freq Error,EVM,Origin Offset,Spectrum Flatness
LTE_TxQuality=Band (),Channel (),Ch_BW (MHz),UL_Start_RB (),UL_Num_RB (),AvgTxPwr (dBm),AvgTxPwr Min,AvgTxPwr Max
LTE_TxQuality_Show=LTE_TxQuality Band:{0},Channel:{1},{2},{3},{4},TxPwr:{5}({6} ~ {7})


Freq Error=UL_Desc (),OriginalFreqErr (ppm),OriginalFreqErrHz (Hz),AvgFreqErr (ppm),AvgFreqErr Min,AvgFreqErr Max,ExtremeFreqErr (ppm),ExtremeFreqErr Min,ExtremeFreqErr Max
Freq Error_Show=LTE Freq Error {0},OriginalFreqErr:{1},OriginalFreqErrHz:{2},AvgFreqErr:{3}({4} ~ {5}),ExtremeFreqErr:{6}({7} ~ {8})

EVM=UL_Desc (),AvgEVM (%),AvgEVM Max,MaxEVM (%),MaxEVM Max,AvgEVM_DMRS (%),AvgEVM_DMRS Max,MaxEVM_DMRS (%),MaxEVM_DMRS Max
EVM_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">EVM</b>
EVM_Show=LTE EVM {0},AvgEVM:{1}( ~ {2}),MaxEVM:{3}( ~ {4}),AvgEVM_DMRS:{5}( ~ {6}),MaxEVM_DMRS:{7}( ~ {8})

Origin Offset=UL_Desc (),_AvgOrigOffset_ (dBc),_AvgOrigOffset_ Max,_MaxOrigOffset_ (dBc),_MaxOrigOffset_ Max
Origin Offset_Show={0},_AvgOrigOffset_:{1}( ~ {2}),_MaxOrigOffset_:{3}( ~ {4})

Spectrum Flatness=UL_Desc (),Spec Flat R1 (dB p-p),Spec Flat R1 Max,Spec Flat R2 (dB p-p),Spec Flat R2 Max,Spec Flat R12 (dB),Spec Flat R12 Max,Spec Flat R21 (dB),Spec Flat R21 Max
Spectrum Flatness_Show=LTE Spectrum Flatness {0},Spec Flat R1:{1}( ~ {2}),Spec Flat R2:{3}( ~ {4}),Spec Flat R12:{5}( ~ {6}),Spec Flat R21:{7}( ~ {8})

[LTE_OccupiedBandwidth]
TableTitles=OBW
OBW=Band (),Channel (),Ch_BW (MHz),UL_Start_RB (),UL_Num_RB (),MaxOccupiedBW (MHz),MaxOccupiedBW Max
OBW_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">OBW</b>
OBW_Show=LTE OBW Band:{0},Channel:{1},{2},{3},{4},MaxOccupiedBW:{5}( ~ {6})

[LTE_SpectrumEmissionMask]
TableTitles=SEM_Detail

;SEM=Band (),Channel (),Ch_BW (MHz),UL_Start_RB (),UL_Num_RB 
;SEM_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">SEM</b>
;SEM_Show=

SEM_Detail=UL_Desc (),OOB Power (dBm),OOB Power Max
SEM_Detail_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">SEM_Detail</b>
SEM_Detail_Show=LTE SEM {0},OOB Power:{1}( ~ {2})

[LTE_ACLR]
TableTitles=UTRA ACLR

UTRA ACLR=Band (),Channel (),Ch_BW (MHz),UL_Start_RB (),UL_Num_RB (),UTRA ACLR (dB),UTRA ACLR Min,UTRA ACLR Extreme (dB),UTRA ACLR Extreme Min,E-UTRA_ACLR (),E-UTRA_ACLR Min,E-UTRA_ACLR_Extreme (),E-UTRA_ACLR_Extreme Min
UTRA ACLR_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">UTRA ACLR</b>
UTRA ACLR_Show=LTE ACLR Band:{0},Channel:{1},{2},{3},{4},UTRA ACLR:{5}({6} ~ ),UTRA ACLR Extreme:{7}({8} ~ ),E-UTRA_ACLR:{9}({10} ~ ),E-UTRA_ACLR_Extreme:{11}({12} ~ )

[LTE_TxPower]
TableTitles=LTE_TxPower

LTE_TxPower=Band (),Channel (),Ch_BW (MHz),UL_Start_RB (),UL_Num_RB (),AvgTxPwr (dBm),AvgTxPwr Min,AvgTxPwr Max
LTE_TxPower_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">LTE_TxPower</b>
LTE_TxPower_Show=LTE_TxPower Band:{0},Channel:{1},{2},{3},{4},TxPwr:{5}({6} ~ {7})

[LTE_RFCalVerification_Rx0]
TableTitles=LTE_RFCalVerification_Rx0
LTE_RFCalVerification_Rx0=Band (),Channel (),Ch_BW (MHz),UL_Start_RB (),UL_Num_RB (),RxError0 (dB),RxError0 Min,RxError0 Max,RxAGC0 (dBm),RxAGC0 Min,RxAGC0 Max
LTE_RFCalVerification_Rx0_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">LTE_RFCalVerification</b>
LTE_RFCalVerification_Rx0_Show=LTE RX0 Band:{0},Channel:{1},{2},{3},{4},RxError0:{5}({6} ~ {7}),RxAGC0:{8}({9} ~ {10})


[LTE_RFCalVerification_Rx1]
TableTitles=LTE_RFCalVerification_Rx1
LTE_RFCalVerification_Rx1=Band (),Channel (),Ch_BW (MHz),UL_Start_RB (),UL_Num_RB (),RxError1 (dB),RxError1 Min,RxError1 Max,RxAGC1 (dBm),RxAGC1 Min,RxAGC1 Max
LTE_RFCalVerification_Rx1_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">LTE_RFCalVerification</b>
LTE_RFCalVerification_Rx1_Show=LTE RX1 Band:{0},Channel:{1},{2},{3},{4},RxError1:{5}({6} ~ {7}),RxAGC1:{8}({9} ~ {10})

[LTE_EstimatedSensitivity_Rx0]
TableTitles=LTE_EstimatedSensitivity_Rx0
LTE_EstimatedSensitivity_Rx0=Band (),Channel (),Ch_BW (MHz),UL_Start_RB (),UL_Num_RB (),Rx Level (dBm),Rx Level Min,Rx Level Max,CtoN  (dB),CtoN  Min,CtoN_Max (dB),CtoN_Min (dB),CtoN_MaxtoMin_Delta (dB),CtoN_MaxtoMin_Delta Max,Sensitivity (dBm),Sensitivity Max
LTE_EstimatedSensitivity_Rx0_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">LTE_EstimatedSensitivity</b>
LTE_EstimatedSensitivity_Rx0_Show=LTE RX0 Band:{0},Channel:{1},{2},{3},{4},Rx Level:{5}({6} ~ {7}),CtoN:{8}({9} ~ ),CtoN_MaxtoMin_Delta:{10}-{11}={12}{ ~ {13}},Sensitivity:{14}( ~ {15})

[LTE_EstimatedSensitivity_Rx1]
TableTitles=LTE_EstimatedSensitivity_Rx1
LTE_EstimatedSensitivity_Rx1=Band (),Channel (),Ch_BW (MHz),UL_Start_RB (),UL_Num_RB (),Rx Level (dBm),Rx Level Min,Rx Level Max,CtoN  (dB),CtoN  Min,CtoN_Max (dB),CtoN_Min (dB),CtoN_MaxtoMin_Delta (dB),CtoN_MaxtoMin_Delta Max,Sensitivity (dBm),Sensitivity Max
LTE_EstimatedSensitivity_Rx1_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">LTE_EstimatedSensitivity</b>
LTE_EstimatedSensitivity_Rx1_Show=LTE RX1 Band:{0},Channel:{1},{2},{3},{4},Rx Level:{5}({6} ~ {7}),CtoN:{8}({9} ~ ),CtoN_MaxtoMin_Delta:{10}-{11}={12}{ ~ {13}},Sensitivity:{14}( ~ {15})

[NR5G_MaxPower]
TableTitles=NR5G_MaxPower
NR5G_MaxPower=Band (),UL Center Channel ARFCN (),SCS (KHz),UplinkBandwidthList (MHz),UL StartRB (),UL NumRB (),Tx Power (dBm),Tx Power Min,Tx Power Max
NR5G_MaxPower_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">NR5G_MaxPower</b>
NR5G_MaxPower_Show=NR5G_MaxPower_Show Band:{0},UL_Channel:{1},{2},{3},{4},{5},TxPwr:{6}({7} ~ {8})

[NR5G_RFCalVerification]
TableTitles=NR5G_TxCalVerification
NR5G_TxCalVerification=Band (),UL Center Channel ARFCN (),SCS (KHz),UplinkBandwidthList (MHz),UL StartRB (),UL NumRB (),Tx Error (dB),Tx Error Min,Tx Error Max,Tx Power (dBm),Tx Power Min,Tx Power Max
NR5G_TxCalVerification_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">NR5G_TxCalVerification</b>
NR5G_TxCalVerification_Show=NR5G_TxCalVerification Band:{0},Channel:{1},{2},{3},{4},{5},Tx Error:{6}({7} ~ {8}),Tx Power:{9}({10} ~ {11})

[NR5G_TxMod]
TableTitles=Freq Error,EVM,Spectrum Flatness
;NR5G_TxMod=Band (),UL Center Channel ARFCN (),SCS (KHz),UplinkBandwidthList (MHz),UL StartRB (),UL NumRB ()
;NR5G_TxMod_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">NR5G_TxMod</b>
;NR5G_TxMod_Show=NR5G_TxMod Band:{0},Channel:{1},{2},{3},{4},{5}

Freq Error=UL Desc (),Pre AvgFreqErr (ppm),Tx Frequency Error (ppm),Tx Frequency Error Min,Tx Frequency Error Max,ExtremeFreqErr (ppm),ExtremeFreqErr Min,ExtremeFreqErr Max
Freq Error_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">Freq Error</b>
Freq Error_Show=NR5G Freq Error {0},Pre AvgFreqErr:{1},Tx Frequency Error:{2}({3} ~ {4}),ExtremeFreqErr:{5}({6} ~ {7})

EVM=UL Desc (),Tx Data EVM (%),Tx Data EVM Max,Tx DMRS EVM (%),Tx DMRS EVM Max
EVM_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">EVM</b>
EVM_Show=NR5G EVM {0},Tx Data EVM:{1}( ~ {2}),Tx DMRS EVM:{3}( ~ {4})

Spectrum Flatness=UL Desc (),Ripple_Range_1 (dB p-p),Ripple_Range_1 Max,Ripple_Range_2 (dB p-p),Ripple_Range_2 Max
Spectrum Flatness_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">Spectrum Flatness</b>
Spectrum Flatness_Show=NR5G Spectrum Flatness {0},Ripple_Range_1:{1}( ~ {2}),Ripple_Range_2:{3}( ~ {4})

[NR5G_TxOBW]
TableTitles=OBW

;SEM=Band (),Channel (),Ch_BW (MHz),UL_Start_RB (),UL_Num_RB 
;SEM_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">SEM</b>
;SEM_Show=

OBW=Band (),UL Center Channel ARFCN (),SCS (KHz),UplinkBandwidthList (MHz),UL StartRB (),UL NumRB (),OBW (MHz),OBW Max
OBW_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">OBW</b>
OBW_Show=NR5G OBW Band:{0},Channel:{1},{2},{3},{4},{5},OBW:{6}( ~ {7})

[NR5G_TxSEM]
TableTitles=SEM,SEM Detail

SEM=Band (),UL Center Channel ARFCN (),SCS (KHz),UplinkBandwidthList (MHz),UL StartRB (),UL NumRB (),Worst SEM Margin (),Worst SEM Margin Min
SEM_HtmlFlag=<br xmlns:msxsl="urn:schemas-microsoft-com:xslt"><b xmlns:msxsl="urn:schemas-microsoft-com:xslt">SEM</b>
SEM_Show=NR5G SEM Band:{0},Channel:{1},{2},{3},{4},{5},Worst SEM Margin:{6}({7} ~ )

SEM Detail=UL Desc (),OOB Power (dBm),OOB Power Max,OOB Offset (MHz)
SEM Detail_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">SEM Detail</b>
SEM Detail_Show=NR5G SEM Detail {0},OOB Power:{1}( ~ {2}),{3}

[NR5G_TxACLR]
TableTitles=NR5G_TxACLR

NR5G_TxACLR=UL Desc (),Tx ACLR (dB),Tx ACLR Min,Tx ACLR worst (dB),Tx ACLR worst Min
NR5G_TxACLR_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">Tx ACLR</b>
NR5G_TxACLR_Show=NR5G Tx ACLR {0},ACLR:{1}({2} ~ ),ACLR worst:{3}({4} ~ )

[NR5G_RFCalVerification_Rx0]
TableTitles=NR5G_RFCalVerification_Rx0
NR5G_RFCalVerification_Rx0=Band (),UL Center Channel ARFCN (),SCS (KHz),UplinkBandwidthList (MHz),DL Power (dBm),UL StartRB (),UL NumRB (),RxAGC0 (dBm),RxError0 (dB),RxError0 Min,RxError0 Max
NR5G_RFCalVerification_Rx0_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">SUB6_RFCalVerification</b
NR5G_RFCalVerification_Rx0_Show=NR5G RFCalVerification Rx0 Band:{0},Channel:{1},{2},{3},DL Power:{4},{5},{6},{7},RxError0:{8}({9} ~ {10})


[NR5G_RFCalVerification_Rx1]
TableTitles=NR5G_RFCalVerification_Rx1
NR5G_RFCalVerification_Rx1=Band (),UL Center Channel ARFCN (),SCS (KHz),UplinkBandwidthList (MHz),DL Power (dBm),UL StartRB (),UL NumRB (),RxAGC1 (dBm),RxError1 (dB),RxError1 Min,RxError1 Max
NR5G_RFCalVerification_Rx1_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">SUB6_RFCalVerification</b
NR5G_RFCalVerification_Rx1_Show=NR5G RFCalVerification Rx1 Band:{0},Channel:{1},{2},{3},DL Power:{4},{5},{6},{7},RxError1:{8}({9} ~ {10})

[NR5G_RFCalVerification_Rx2]
TableTitles=NR5G_RFCalVerification_Rx2
NR5G_RFCalVerification_Rx2=Band (),UL Center Channel ARFCN (),SCS (KHz),UplinkBandwidthList (MHz),DL Power (dBm),UL StartRB (),UL NumRB (),RxAGC2 (dBm),RxError2 (dB),RxError2 Min,RxError2 Max
NR5G_RFCalVerification_Rx2_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">SUB6_RFCalVerification</b
NR5G_RFCalVerification_Rx2_Show=NR5G RFCalVerification Rx2 Band:{0},Channel:{1},{2},{3},DL Power:{4},{5},{6},{7},RxError2:{8}({9} ~ {10})

[NR5G_RFCalVerification_Rx3]
TableTitles=NR5G_RFCalVerification_Rx3
NR5G_RFCalVerification_Rx3=Band (),UL Center Channel ARFCN (),SCS (KHz),UplinkBandwidthList (MHz),DL Power (dBm),UL StartRB (),UL NumRB (),RxAGC3 (dBm),RxError3 (dB),RxError3 Min,RxError3 Max
NR5G_RFCalVerification_Rx3_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">SUB6_RFCalVerification</b
NR5G_RFCalVerification_Rx3_Show=NR5G RFCalVerification Rx3 Band:{0},Channel:{1},{2},{3},DL Power:{4},{5},{6},{7},RxError3:{8}({9} ~ {10})

[NR5G_EstimatedSensitivity_Rx0]
TableTitles=NR5G_EstimatedSensitivity_Rx0
NR5G_EstimatedSensitivity_Rx0=Band (),UL Center Channel ARFCN (),SCS (KHz),UplinkBandwidthList (MHz),DL Power (dBm),UL StartRB (),UL NumRB (),Rx0 Level (dBm),Rx0 Level Min,Rx0 Level Max,Est Sensitivity RX 0 (dBm),Est Sensitivity RX 0 Max,CNR Rx 0 (dB),Peak Freq Rx 0 (MHz)
NR5G_EstimatedSensitivity_Rx0_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">NR5G_EstimatedSensitivity</b>
NR5G_EstimatedSensitivity_Rx0_Show=LNR5G EstimatedSensitivity Rx0 Band:{0},Channel:{1},{2},{3},{4},{5},{6},Rx0 Level:{7}({8} ~ {9}),Est Sensitivity RX 0:{10}( ~ {11}),{12},{13}

[NR5G_EstimatedSensitivity_Rx1]
TableTitles=NR5G_EstimatedSensitivity_Rx1
NR5G_EstimatedSensitivity_Rx1=Band (),UL Center Channel ARFCN (),SCS (KHz),UplinkBandwidthList (MHz),DL Power (dBm),UL StartRB (),UL NumRB (),Rx1 Level (dBm),Rx1 Level Min,Rx1 Level Max,Est Sensitivity RX 1 (dBm),Est Sensitivity RX 1 Max,CNR Rx 1 (dB),Peak Freq Rx 1 (MHz)
NR5G_EstimatedSensitivity_Rx1_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">NR5G_EstimatedSensitivity</b>
NR5G_EstimatedSensitivity_Rx1_Show=LNR5G EstimatedSensitivity Rx1 Band:{0},Channel:{1},{2},{3},{4},{5},{6},Rx1 Level:{7}({8} ~ {9}),Est Sensitivity RX 1:{10}( ~ {11}),{12},{13}

[NR5G_EstimatedSensitivity_Rx2]
TableTitles=NR5G_EstimatedSensitivity_Rx2
NR5G_EstimatedSensitivity_Rx2=Band (),UL Center Channel ARFCN (),SCS (KHz),UplinkBandwidthList (MHz),DL Power (dBm),UL StartRB (),UL NumRB (),Rx2 Level (dBm),Rx2 Level Min,Rx2 Level Max,Est Sensitivity RX 2 (dBm),Est Sensitivity RX 2 Max,CNR Rx 2 (dB),Peak Freq Rx 2 (MHz)
NR5G_EstimatedSensitivity_Rx2_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">NR5G_EstimatedSensitivity</b>
NR5G_EstimatedSensitivity_Rx2_Show=LNR5G EstimatedSensitivity Rx2 Band:{0},Channel:{1},{2},{3},{4},{5},{6},Rx1 Level:{7}({8} ~ {9}),Est Sensitivity RX 2:{10}( ~ {11}),{12},{13}


[NR5G_EstimatedSensitivity_Rx3]
TableTitles=NR5G_EstimatedSensitivity_Rx3
NR5G_EstimatedSensitivity_Rx3=Band (),UL Center Channel ARFCN (),SCS (KHz),UplinkBandwidthList (MHz),DL Power (dBm),UL StartRB (),UL NumRB (),Rx3 Level (dBm),Rx3 Level Min,Rx3 Level Max,Est Sensitivity RX 3 (dBm),Est Sensitivity RX 3 Max,CNR Rx 3 (dB),Peak Freq Rx 3 (MHz)
NR5G_EstimatedSensitivity_Rx3_HtmlFlag=<b xmlns:msxsl="urn:schemas-microsoft-com:xslt">NR5G_EstimatedSensitivity</b>
NR5G_EstimatedSensitivity_Rx3_Show=LNR5G EstimatedSensitivity Rx3 Band:{0},Channel:{1},{2},{3},{4},{5},{6},Rx1 Level:{7}({8} ~ {9}),Est Sensitivity RX 3:{10}( ~ {11}),{12},{13}

