#pragma once

namespace JGW
{
    enum E_USER_DEFINE_LOG_TYPE
    {
        E_UNKNOW_USER_DEFINE = -1,
        E_USER_DEFINE_HTMLFILEPATH = 0,
		E_TSE_SHOW_CONTENT_INFO = 1,
        E_TSE_SHOW_TEST_INFO_TO_RICHEDIT = 2,
        E_COPYDATA_TSE_SHOW_IDEL_BUSY_LIST_TEST_STATUS = 3,
        E_COPYDATA_TSE_SHOW_FAIL_LIST_TEST_STATUS = 4,
        E_COPYDATA_TSE_SHOW_PASS_LIST_TEST_STATUS = 5
    };
}
//! 应用程序路径
#define APPLICATION_PATH L"APPLICATION_PATH"
//! 时间年月日  比如2018-09-01
#define TIME_YEAR_MON_DAY L"TIME_YEAR_MON_DAY"
//!
#define TSE_TEST_PROJECT_NAME L"TSE_TEST_PROJECT_NAME"
//!  Global Environment Config 
#define TSE_GLOBAL_ENVIRONMENT_CONFIG_FILE_PATH L"TSE_GLOBAL_ENVIRONMENT_CONFIG_FILE_PATH"

#define MULTIUNIT_TSE_TEST L"MULTIUNIT_TSE_TEST"
//! 
#define TSE_SUITE_FILE_PATH L"TSE_SUITE_FILE_PATH"
//! 
#define TSE_SUITE_FILE_PATH_A "TSE_SUITE_FILE_PATH"
//! 
#define TSE_ERROR_STOP L"TSE_ERROR_STOP"
//! 
#define TSE_ERROR_STOP_A "TSE_ERROR_STOP"
//! TSE 模块名称
#define TSE_CONFIG_MODULENAME L"ModuleName"
//! TSE 类名
#define TSE_CONFIG_REALNAME L"RealName"
//! TSE 重测次数
#define TSE_CONFIG_RETRYCOUNT L"RetryCount"
//!
#define TSE_CONFIG_TEST_NAME L"TestName"
//! IntervalTimeMS 测试失败间隔测试时间 某些测试可能需要等待测试完成时间
#define TSE_CONFIG_INTERVALTIMEMS L"IntervalTimeMS"
//! 环境变量
#define TSE_GLOBAL_ENVIRONMENT L"TSE_GLOBAL_ENVIRONMENT"
//! Log服务
#define TSE_LOG_SERVICES L"TSE_LOG_SERVICES"
//! Test Status服务
#define TSE_TESTSTATUS_SERVICES L"TSE_TESTSTATUS_SERVICES"
//!
#define TSE_MODULE_GLOBAL_RESOURCES_CLSSNAM "CTSE_GlobalResources"
//!
#define TSE_GLOBAL_MAIN_HWND L"TSE_GLOBAL_MAIN_HWND"
//!
#define TSE_GLOBAL_MAIN_HWND_A "TSE_GLOBAL_MAIN_HWND"
//! 
#define TSE_FTM_CLIENT_SOCKET_IP_ADDRESS L"TSE_FTM_CLIENT_SOCKET_IP_ADDRESS"
//! SN
#define TSE_SN L"TSE_SN"
//! IMEI
#define TSE_IMEI L"TSE_IMEI"
//! WIFI MAC
#define TSE_WIFI_MAC L"TSE_WIFI_MAC"
//! 网口 MAC
#define TSE_ETH0_MAC L"TSE_ETH0_MAC"
//! 蓝牙地址
#define TSE_BT L"TSE_BT"
//! 
#define TSE_2_4_SSID L"TSE_2_4_SSID"
//!
#define TSE_2_4_PASSWORD L"TSE_2_4_PASSWORD"
//! 
#define TSE_5_SSID L"TSE_5_SSID"
//!
#define TSE_5_PASSWORD L"TSE_5_PASSWORD"
//! 
#define TSE_AD_SSID L"TSE_AD_SSID"
//!
#define TSE_AD_PASSWORD L"TSE_AD_PASSWORD"
//! 
#define TSE_FTM_CONNECT_MODE L"TSE_FTM_CONNECT_MODE"

#define TSE_FTM_CLIENT_PORT L"TSE_FTM_CLIENT_PORT"

//! Download 
#define TSE_DOWNLOAD_PORT_PARAM L"TSE_DOWNLOAD_PORT_PARAM"

#define TSE_DOWNLOAD_PATH_PARAM L"TSE_DOWNLOAD_PATH_PARAM"

#define TSE_SAHARA_FIREHOSE_IMAGE_PARAM L"TSE_SAHARA_FIREHOSE_IMAGE_PARAM"

#define TSE_DOWNLOAD_PROVISION_XML_NAME_PARAM L"TSE_DOWNLOAD_PROVISION_XML_NAME_PARAM"

#define TSE_RAWPROGRAM_XML_NAMES_PARAM L"TSE_RAWPROGRAM_XML_NAMES_PARAM"

#define TSE_PATCH_XML_NAMES_PARAM L"TSE_PATCH_XML_NAMES_PARAM"

#define TSE_RESET_ENABLE_PARAM L"TSE_RESET_ENABLE_PARAM"
//! 当前TSE测试结果集  1 : PASS  0 : FAIL
#define TSE_TEST_RESULT L"TSE_TEST_RESULT"
//! 重新测试标记位  --- 重测标记默认不会重新过站点
#define TSE_MES_RETEST_FLAG L"TSE_MES_RETEST_FLAG"
//！ MES 订单
#define TSE_MES_TASK_NUMBER L"TSE_MES_TASK_NUMBER"
//!
#define TSE_PRS_DeviceBootMode L"TSE_PRS_DeviceBootMode"
//!
#define TSE_QIA_WINDOW_HANLDE L"TSE_QIA_WINDOW_HANLDE"
//! 
#define TSE_QIA_IS_RUNNING_FLAG L"TSE_QIA_IS_RUNNING_FLAG"
//! 
#define TSE_QIA_TEST_RESULT L"TSE_QIA_TEST_RESULT"
//!
#define TSE_QIA_TEST_DONE L"TSE_QIA_TEST_DONE"
//! QIA HTML Test File
#define TSE_QIA_HTML_TEST_FILE L"TSE_QIA_HTML_TEST_FILE"