[MAIN]
WKE_HTML=html\\echarts_speed.html
;0 : Server 1 : Client
TerminalType =1
;0 : TCP 1 : UDP
ProtocolType =0
IperfIP =192.168.1.102
SSHIP =192.168.1.2
CellphoneIP =0.0.0.0
IsUseCellphoneIP =0
TestTimes =2000
Threads =4
ExtraParameters =
TestDelayTime=1
Check11ADConnectCommand=iw wlan0 station dump
11ADConnectedFindString=signal
LOG_PREFIX=
