[USB]
USB_COUNT = 23

;ADB MODEM COM DISK LAN
[1]
USB_GUID = ADB
USB_VID = 05C6
USB_PID = 9091
USB_DEV_MODE = ADB
USB_SERVICE = WinUSB
USB_DEVICEDES = Android Composite ADB Interface
;USB_CLASS = 

;高通MODEM口
[2]
USB_GUID = MODEM
USB_VID = 05C6
USB_PID = 9091
USB_DEV_MODE = MODEM
USB_SERVICE = Modem
USB_DEVICEDES = Qualcomm HS-USB Modem 9091

;高通DIAG口
[3]
USB_GUID = COM
USB_VID = 05C6
USB_PID = 9091
USB_DEV_MODE = DIAG
USB_SERVICE = qcusbser
USB_DEVICEDES = Qualcomm HS-USB Diagnostics 9091

;高通9008端口
[4]
USB_GUID = COM
USB_VID = 05C6
USB_PID = 9008
USB_DEV_MODE = DOWNLOADER
USB_SERVICE = qcusbser
USB_DEVICEDES = Qualcomm HS-USB QDLoader 9008

;安卓FASTBOOT端口
[5]
USB_GUID = ADB
USB_VID = 18D1
USB_PID = D00D
USB_DEV_MODE = FASTBOOT
USB_SERVICE = WinUSB
USB_DEVICEDES = Android ADB Interface


;9025端口
[6]
USB_GUID = COM
USB_VID = 05C6
USB_PID = 9025
USB_DEV_MODE = DIAG
USB_SERVICE = qcusbser
USB_DEVICEDES = Qualcomm HS-USB Diagnostics 9025

;9025 ADB 端口
[7]
USB_GUID = ADB
USB_VID = 05C6
USB_PID = 9025
USB_DEV_MODE = ADB
USB_SERVICE = WinUSB
USB_DEVICEDES = Android Composite ADB Interface

;9025 MODEM 端口
[8]
USB_GUID = MODEM
USB_VID = 05C6
USB_PID = 9025
USB_DEV_MODE = MODEM
USB_SERVICE = Modem
USB_DEVICEDES = Qualcomm HS-USB Android Modem 9025

;通用MODEM端口识别  MODEM
[9]
USB_GUID = MODEM
;USB_VID = 05C6
;USB_PID = 9025
USB_DEV_MODE = MODEM
USB_SERVICE = Modem
;USB_DEVICEDES = Qualcomm HS-USB Android Modem 9025

;通用Daig端口识别  MODEM
[10]
USB_GUID = COM
;USB_VID = 05C6
;USB_PID = 9025
USB_DEV_MODE = DIAG
USB_SERVICE = qcusbser
;USB_DEVICEDES = Qualcomm HS-USB Diagnostics 9025

;peraso port
[11]
USB_GUID = COM
USB_VID = 2932
USB_PID = 4001
USB_DEV_MODE = DIAG
USB_SERVICE = usbser
;USB_DEVICEDES = USB Networks Modem

;peraso port
[12]
USB_GUID = COM
USB_VID = 2932
USB_PID = F001
USB_DEV_MODE = DOWNLOADER
USB_SERVICE = usbser
USB_DEVICEDES = Peraso Falcon Bootloader Virtual Com Port

;peraso port
[13]
USB_GUID = COM
USB_VID = 2932
USB_PID = F110
USB_DEV_MODE = DIAG
USB_SERVICE = usbser
USB_DEVICEDES = Peraso Falcon Bootloader Virtual Com Port

;高通DIAG口
[14]
USB_GUID = COM
USB_VID = 05C6
USB_PID = 901D
USB_DEV_MODE = DIAG
USB_SERVICE = qcusbser
USB_DEVICEDES = Qualcomm HS-USB Android DIAG 901D

[15]
USB_GUID = ADB
USB_VID = 05C6
USB_PID = 901D
USB_DEV_MODE = ADB
USB_SERVICE = WinUSB
USB_DEVICEDES = Android Composite ADB Interface


;peraso port
[16]
USB_GUID = COM
USB_VID = 2932
USB_PID = F100
USB_DEV_MODE = DIAG
USB_SERVICE = usbser
;USB_DEVICEDES = Peraso Falcon Bootloader Virtual Com Port

[17]
USB_GUID = ADB
USB_VID = 05C6
USB_PID = 9039
USB_DEV_MODE = ADB
USB_SERVICE = WinUSB
USB_DEVICEDES = Android Composite ADB Interface
;USB_CLASS = 


[18]
USB_GUID = ADB
USB_VID = 18D1
USB_PID = 4EE7
USB_DEV_MODE = ADB
USB_SERVICE = WinUSB
USB_DEVICEDES = Android Composite ADB Interface

[19]
USB_GUID = COM
USB_VID = 2932
USB_PID = 0710
USB_DEV_MODE = DIAG
USB_SERVICE = usbser

[20]
USB_GUID = COM
USB_VID = 0403
USB_PID = 6001
USB_DEV_MODE = DIAG
USB_SERVICE = 
;peraso port

[21]
USB_GUID = COM
USB_VID = 2932
USB_PID = F600
USB_DEV_MODE = DIAG
USB_SERVICE = usbser
;USB_DEVICEDES = Peraso Falcon Bootloader Virtual Com Port

[22]
USB_GUID = COM
USB_VID = 10C4
USB_PID = EA60
USB_DEV_MODE = DIAG
USB_SERVICE = 

[23]
USB_GUID = COM
USB_VID = 067B
USB_PID = 2303
USB_DEV_MODE = DIAG
USB_SERVICE = 