;GPIB:NIGPIB/AGILENTGPIB
[GPIB]
BoardID=0
PrimAddress=20
ScndAddress=0
PartialClassName=NIGPIB

[VISA]
VisaAddress=TCPIP0::DESKTOP-AOO97OK::inst1::INSTR

[TCPIP]
IPAddress=169.254.132.15
SourceAddress=
Port=5025
SubInstrument=0

[MONITOR]
SURPORT_MODEL = SCPI
MODEL =CMW500
ADDRESS =VISA
